name: deploy-toy-website

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true 

    - name: Deploy resources
      uses: Azure/data-factory-deploy-action@v1.2.0
      with:
        resourceGroupName: shirtest
        dataFactoryName: shirtest-df-prod
        armTemplateFile: shirtest-df\ARMTemplateForFactory.json
        armTemplateParametersFile: shirtest-df\ARMTemplateParametersForFactory.json
      # additionalParameters: 'key1=value key2=value keyN=value' [optional]
      # skipAzModuleInstallation: true [optional]