name: deploy-adf

concurrency: adf

on:
  push:
    branches:
      - main
    paths:
      - 'adf-iac-dev/'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        #client-id: ${{ secrets.AZURE_CLIENT_ID }}
        #tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        #subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true 

    - name: Deploy resources
      uses: Azure/data-factory-deploy-action@v1.2.0
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: adf-iac-prod
        dataFactoryName: adf-iac-prod
        armTemplateFile: adf-iac-dev/ARMTemplateForFactory.json
        armTemplateParametersFile: adf-iac-dev/ARMTemplateParametersForFactory.json
