name: Deploy Data Factory

concurrency: adf-deploy-workflow

env:
    RESOURCEGROUP_NAME: name-rg
    DATAFACTORY_NAME: name-df-prod
    ARMTEMPLATEFOLDER_NAME: name-df-devtest

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true 

    - name: Deploy resources
      uses: Azure/data-factory-deploy-action@v1.2.0
      with:
        resourceGroupName: ${{ env.RESOURCEGROUP_NAME }}
        dataFactoryName: ${{ env.DATAFACTORY_NAME }}
        armTemplateFile: ${{ env.ARMTEMPLATEFOLDER_NAME }}/ARMTemplateForFactory.json
        armTemplateParametersFile: ${{ env.ARMTEMPLATEFOLDER_NAME }}/ARMTemplateParametersForFactory.json
